# Uncomment the next line to define a global platform for your project
# platform :ios, '12.1'

target 'Shopping List' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shopping List
  pod 'Firebase'
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseDatabase'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

  target 'Shopping ListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Shopping ListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
