# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shopping List' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shopping List
pod 'Firebase/Core'
pod 'Firebase/Auth'

  target 'Shopping ListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Shopping ListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
